
;; #+html: </details>
;; #+html: <details><summary>packages.el</summary>

;; [[file:config.org::*File Headers][File Headers:2]]
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file, config.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
;; File Headers:2 ends here

;; Capturing links to external applications

;; =org-mac-link= implements the ability to grab links from different Mac apps and insert them in the file. Bind =C-c g= to call =org-mac-grab-link= to choose an application and insert a link.

;; [[file:config.org::*Capturing links to external applications][Capturing links to external applications:1]]
(when IS-MAC
  (package! org-mac-link))
;; Capturing links to external applications:1 ends here

;; Themes

;; First, let's get all the themes loaded.

;; [[file:config.org::*Themes][Themes:1]]
(package! doom-themes)
;; Themes:1 ends here

;; [[https://github.com/awth13/org-appear][Org-Appear]]

;; Reveals hidden entities such as emphasis markers when moving the cursor over them.

;; [[file:config.org::*\[\[https:/github.com/awth13/org-appear\]\[Org-Appear\]\]][[[https://github.com/awth13/org-appear][Org-Appear]]:1]]
(package! org-appear
  :recipe (:host github
           :repo "awth13/org-appear"))
;; [[https://github.com/awth13/org-appear][Org-Appear]]:1 ends here

;; [[https://github.com/yilkalargaw/org-auto-tangle][Org-Auto-Tangle]]

;; Automatically runs =org-babel-tangle= upon saving any =org-mode= buffer.

;; [[file:config.org::*\[\[https:/github.com/yilkalargaw/org-auto-tangle\]\[Org-Auto-Tangle\]\]][[[https://github.com/yilkalargaw/org-auto-tangle][Org-Auto-Tangle]]:1]]
(package! org-auto-tangle)
;; [[https://github.com/yilkalargaw/org-auto-tangle][Org-Auto-Tangle]]:1 ends here

;; [[https://github.com/org-roam/org-roam-ui][Org-Roam-UI]]

;; Renders the =org-roam= Zettelkasten in a web browser.

;; First, we need to unpin Doom's =org-roam= to ensure we have the latest and greatest.

;; [[file:config.org::*\[\[https:/github.com/org-roam/org-roam-ui\]\[Org-Roam-UI\]\]][[[https://github.com/org-roam/org-roam-ui][Org-Roam-UI]]:1]]
(unpin! org-roam)
(package! org-roam-ui)
;; [[https://github.com/org-roam/org-roam-ui][Org-Roam-UI]]:1 ends here

;; [[https://github.com/veripool/verilog-mode][Verilog-Mode]]

;; Provides basic support for Verilog editing, including autos.

;; [[file:config.org::*\[\[https:/github.com/veripool/verilog-mode\]\[Verilog-Mode\]\]][[[https://github.com/veripool/verilog-mode][Verilog-Mode]]:1]]
(package! verilog-mode)
;; [[https://github.com/veripool/verilog-mode][Verilog-Mode]]:1 ends here

;; [[https://github.com/gmlarumbe/verilog-ext][Verilog-Ext]]

;; Provides advanced editing features for Verilog or SystemVerilog code, including tree-sitter.

;; [[file:config.org::*\[\[https:/github.com/gmlarumbe/verilog-ext\]\[Verilog-Ext\]\]][[[https://github.com/gmlarumbe/verilog-ext][Verilog-Ext]]:1]]
(package! verilog-ext)
;; [[https://github.com/gmlarumbe/verilog-ext][Verilog-Ext]]:1 ends here
